//APP Action
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGIN_RESPONSE_SUCCESS = 'APP_LOGIN_RESPONSE_SUCCESS'
export const APP_LOGIN_RESPONSE_FAIL = 'APP_LOGIN_RESPONSE_FAIL'
export const APP_LOGOUT = 'APP_LOGOUT'
export const APP_REGISTER= 'APP_REGISTER'
export const APP_REGISTER_SUCCESS= 'APP_REGISTER_SUCCESS'
export const APP_REGISTER_FAIL= 'APP_REGISTER_FAIL'
export const APP_RESET_ERROR = 'APP_RESET_ERROR'

//HOME
export const HOME_GET_LIST = 'HOME_GET_LIST'
export const HOME_GET_LIST_RES_SUCCESS = 'HOME_GET_LIST_RES_SUCCESS'
export const HOME_GET_LIST_RES_FAIL = 'HOME_GET_LIST_RES_FAIL'

//NEWS
export const NEWS_GET_LIST = 'NEWS_GET_LIST'
export const NEWS_GET_LIST_RES_SUCCESS = 'NEWS_GET_LIST_RES_SUCCESS'
export const NEWS_GET_LIST_RES_FAIL = 'NEWS_GET_LIST_RES_FAIL'

//BOOKING
export const BOOKING_ROOM= 'BOOKING_ROOM'
export const BOOKING_ROOM_SUCCESS = 'BOOKING_ROOM_SUCCESS'
export const BOOKING_ROOM_FAIL = 'BOOKING_ROOM_FAIL'
export const BOOKING_ROOM_CONFIRM = 'BOOKING_ROOM_CONFIRM'

//SEARCHING
export const SEARCHING_ROOM= 'SEARCHING_ROOM'
export const SEARCHING_ROOM_SUCCESS = 'SEARCHING_ROOM_SUCCESS'
export const SEARCHING_ROOM_FAIL = 'SEARCHING_ROOM_FAIL'
